# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'image_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_processor.proto\x12\x0eimageprocessor\"=\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x03(\t\"L\n\x0cImageRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"}\n\rImageResponse\x12\x32\n\x07success\x18\x01 \x01(\x0b\x32\x1f.imageprocessor.SuccessResponseH\x00\x12.\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1d.imageprocessor.ErrorResponseH\x00\x42\x08\n\x06result\"=\n\x0fSuccessResponse\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x02 \x01(\t\"\x85\x01\n\rErrorResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.imageprocessor.ProcessStatus\x12\x31\n\x0c\x65rror_detail\x18\x02 \x01(\x0b\x32\x1b.imageprocessor.ErrorDetail\x12\x12\n\nrequest_id\x18\x03 \x01(\t*d\n\rProcessStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x11\n\rINVALID_INPUT\x10\x02\x12\x14\n\x10PROCESSING_ERROR\x10\x03\x12\x11\n\rSTORAGE_ERROR\x10\x04\x32\x64\n\x15ImageProcessorService\x12K\n\x0cProcessImage\x12\x1c.imageprocessor.ImageRequest\x1a\x1d.imageprocessor.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSSTATUS']._serialized_start=508
  _globals['_PROCESSSTATUS']._serialized_end=608
  _globals['_ERRORDETAIL']._serialized_start=41
  _globals['_ERRORDETAIL']._serialized_end=102
  _globals['_IMAGEREQUEST']._serialized_start=104
  _globals['_IMAGEREQUEST']._serialized_end=180
  _globals['_IMAGERESPONSE']._serialized_start=182
  _globals['_IMAGERESPONSE']._serialized_end=307
  _globals['_SUCCESSRESPONSE']._serialized_start=309
  _globals['_SUCCESSRESPONSE']._serialized_end=370
  _globals['_ERRORRESPONSE']._serialized_start=373
  _globals['_ERRORRESPONSE']._serialized_end=506
  _globals['_IMAGEPROCESSORSERVICE']._serialized_start=610
  _globals['_IMAGEPROCESSORSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
